/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { hardwareSecurityKeysDelete } from "../funcs/hardwareSecurityKeysDelete.js";
import { hardwareSecurityKeysList } from "../funcs/hardwareSecurityKeysList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class HardwareSecurityKeys extends ClientSDK {
  /**
   * Delete Security Key
   */
  async delete(
    request: operations.HskDeleteApiRequest,
    options?: RequestOptions,
  ): Promise<operations.HskDeleteApiResponse> {
    return unwrapAsync(hardwareSecurityKeysDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * List Security Keys
   */
  async list(
    request: operations.HskGetListApiRequest,
    options?: RequestOptions,
  ): Promise<operations.HskGetListApiResponse> {
    return unwrapAsync(hardwareSecurityKeysList(
      this,
      request,
      options,
    ));
  }
}
