/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { servicesDelete } from "../funcs/servicesDelete.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Services extends ClientSDK {
  /**
   * Delete Service ⚡
   *
   * @remarks
   * Delete a service.
   */
  async delete(
    request: operations.ServiceDeleteApiRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(servicesDelete(
      this,
      request,
      options,
    ));
  }
}
