workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Authlete API Explorer:
        inputs:
            - location: ./specs/spec1.json
        transformations:
            - removeUnused: true
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/vartana/qwerty/authlete-api-explorer
targets:
    authelete-bundled:
        target: typescript
        source: Authlete API Explorer
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/vartana/qwerty/authlete-api-explorer-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
